spring:
  application:
    name: nacos-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alltest
    username: root
    password: root1234
  cloud:
    nacos:
      discovery:
        server-addr: 81.69.229.201:8848
mybatis-plus:
  mapper-locations: /mapper/*.xml
server:
  port: 3344